name: AWS CLI Action
description: Run aws cli also piped to jq

inputs:
  args:
    description: Command-line arguments to the `aws`
    required: true
  jq-args:
    description: jq arguments to parse the output of aws
    required: false

outputs:
  result:
    description: Result of command

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
  env:
    JQ_ARGS: ${{ inputs.jq-args }}
